name: Building and Pushing Python Image to Google Cloud Platform
on:
  push:
    pull_request:
      - main
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mailchimp-data-science
      PROJECT_ID: ${{ secrets.PROJECT_ID }} 
      APPLICATION_NAME: hello-world-app
      REGION: us-east1
      PROJECT_NUMBER: ${{secrets.PROJECT_NUMBER }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }} 
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    - name: Build & Deploy to Cloud Run 
      run: |-
        gcloud projects add-iam-policy-binding $PROJECT_ID --member="service-$PROJECT_NUMBER@gcp-sa-cloudbuild.iam.gserviceaccount.com" --role="roles/cloudbuild.serviceAgent"
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$IMAGE_NAME --project=$PROJECT_ID
        gcloud run deploy $IMAGE_NAME  --image gcr.io/$PROJECT_ID/$IMAGE_NAME  --platform managed --project=$PROJECT_ID --allow-unauthenticated --region $REGION